backend:
  name: git-gateway
  branch: main
media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "images"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/post
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    path: "{{slug}}/index"
    media_folder: "" # Save images in the post's own folder instead of the static folder
    public_folder: ""
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: SEO Metadata
        name: seo_metadata
        widget: "object"
        collapsed: true
        fields:
          - { label: Meta Title, name: meta_title, widget: string }
          - { label: Meta Description, name: meta_description, widget: string }
  - name: "work" # Used in routes, e.g., /admin/collections/post
    label: "Work" # Used in the UI
    folder: "content/work" # The path to the folder where the documents are stored
    path: "{{slug}}/index"
    media_folder: "" # Save images in the post's own folder instead of the static folder
    public_folder: ""
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Website Preview", name: "website_preview", widget: "image" }
      - { label: "Website URL", name: "website_url", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Feature Post?", name: "featured_post", widget: "boolean", default: true }
  - name: "pages" # Used in routes, e.g., /admin/collections/post
    label: "Pages" # Used in the UI
    files:
      - label: "About"
        name: "about"
        file: "content/about/index.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
      - label: "Resume"
        name: "resume"
        file: "content/resume/index.md"
        fields:
          - { label: Title, name: title, widget: string }
          - { label: Body, name: body, widget: markdown }
  - name: "site_settings"
    label: "Site Settings"
    files:
      - file: "data/footer.json"
        label: Footer
        name: footer
        fields:
          - { label: Title, name: title, widget: string }
      - file: "data/globals.json"
        label: Globals
        name: global
        fields:
          - { label: Logo, name: logo, widget: image }