backend:
  name: git-gateway
  branch: main
media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "images"
collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    fields:
      - label: "SEO Metadata"
        name: "seo"
        widget: "seo_fields" # Use the custom widget
      # Other fields specific to your "Blog" collection

  - name: "work"
    label: "Work"
    folder: "content/work"
    create: true
    fields:
      - label: "SEO Metadata"
        name: "seo"
        widget: "seo_fields" # Use the custom widget
      # Other fields specific to your "Work" collection

  - name: "pages"
    label: "Pages"
    files:
      - label: "About"
        name: "about"
        file: "content/about/index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "SEO Metadata"
            name: "seo"
            widget: "seo_fields" # Use the custom widget
      - label: "Resume"
        name: "resume"
        file: "content/resume/index.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "SEO Metadata"
            name: "seo"
            widget: "seo_fields" # Use the custom widget

  - name: "site_settings"
    label: "Site Settings"
    files:
      - file: "data/footer.json"
        label: Footer
        name: footer
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo_footer, widget: image}
      - file: "data/globals.json"
        label: Globals
        name: global
        fields:
          - {label: Logo, name: logo_global, widget: image}

widgets:
  - name: "seo_fields"
    label: "SEO Fields"
    widget: "object"
    fields:
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Keywords", name: "keywords", widget: "string" }
