backend:
  name: git-gateway
  branch: main
media_folder: "static/images" # Folder where user uploaded files should go
local_backend: true
public_folder: "images"
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/post
    label: "Blog" # Used in the UI
    folder: "content/blog" # The path to the folder where the documents are stored
    path: "{{slug}}/index"
    media_folder: "" # Save images in the post's own folder instead of the static folder
    public_folder: ""
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "work" # Used in routes, e.g., /admin/collections/post
    label: "Work" # Used in the UI
    folder: "content/work" # The path to the folder where the documents are stored
    path: "{{slug}}/index"
    media_folder: "" # Save images in the post's own folder instead of the static folder
    public_folder: ""
    create: true # Allow users to create new documents in this collection
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "Pages" # Used in routes, e.g., /admin/collections/post
    label: "pages" # Used in the UI
    files:
      - label: "About"
        name: "about"
        file: "site/about/index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
      - label: "Resume"
        name: "about"
        file: "site/resume/index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
      - label: "Work"
        name: "work"
        file: "site/work/_index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
      - label: "Blog"
        name: "blog"
        file: "site/blog/_kindex.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}